"""Update field size

Revision ID: 471c229b5743
Revises: 40c005657356
Create Date: 2025-04-30 18:28:09.034622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "471c229b5743"
down_revision: Union[str, None] = "40c005657356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
