"""Add public_uuid field

Revision ID: 1aeff972668a
Revises: 471c229b5743
Create Date: 2025-05-02 01:43:11.897533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1aeff972668a"
down_revision: Union[str, None] = "471c229b5743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checks",
        sa.Column(
            "public_uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_checks_public_uuid"), "checks", ["public_uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checks_public_uuid"), table_name="checks")
    op.drop_column("checks", "public_uuid")
    # ### end Alembic commands ###
